name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: [10.x, 12.x]
        os: [ubuntu-18.04, windows-2019, macOS-10.14]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2.1.1
        with:
          node-version: ${{ matrix.node }}

      - name: Install
        run: |
          yarn install

      - name: Run linting
        shell: bash
        run: |
          yarn nx run-many --target=lint --all=true --parallel=true

      - name: Run testing
        shell: bash
        run: |
          yarn nx run-many --target=test --all=true --parallel=true
